# Generated by Django 4.2 on 2023-04-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FirstSem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=100)),
                ("department", models.CharField(default="", max_length=100)),
                ("ltp", models.CharField(default="", max_length=100)),
                ("offered_for", models.CharField(default="", max_length=100)),
                ("type", models.CharField(default="", max_length=100)),
                ("objectives", models.CharField(default="", max_length=500)),
                ("prerequisite", models.CharField(default="", max_length=100)),
                ("contents", models.CharField(default="", max_length=1000)),
                ("referenceb_books", models.CharField(default="", max_length=500)),
                (
                    "self_mearning_material",
                    models.CharField(default="", max_length=500),
                ),
            ],
        ),
    ]
