# Generated by Django 4.2 on 2023-04-20 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("firstyear", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="FirstSem", new_name="Courses",),
    ]
