# Generated by Django 4.2 on 2023-04-20 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("firstyear", "0002_rename_firstsem_courses"),
    ]

    operations = [
        migrations.RenameModel(old_name="Courses", new_name="Course",),
    ]
