# Generated by Django 4.2 on 2023-04-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstyear", "0003_rename_courses_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="learning_outcome",
            field=models.CharField(default="", max_length=100),
        ),
    ]
