# Generated by Django 4.2 on 2023-04-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstyear", "0004_course_learning_outcome"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_code",
            field=models.CharField(default="", max_length=100),
        ),
    ]
