# Generated by Django 4.2 on 2023-04-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstyear", "0005_course_course_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="prerequisite",
            field=models.CharField(default="Nil", max_length=100),
        ),
    ]
