# Generated by Django 4.2 on 2023-04-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstyear", "0006_alter_course_prerequisite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="contents",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_code",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="course",
            name="department",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="course",
            name="learning_outcome",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="course",
            name="ltp",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="course",
            name="objectives",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="course",
            name="offered_for",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="course",
            name="prerequisite",
            field=models.CharField(blank=True, default="Nil", max_length=100),
        ),
        migrations.AlterField(
            model_name="course",
            name="referenceb_books",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="course",
            name="self_mearning_material",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="course",
            name="type",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
