# Generated by Django 4.2 on 2023-04-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstyear", "0007_alter_course_contents_alter_course_course_code_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course", old_name="contents", new_name="content1",
        ),
        migrations.RenameField(
            model_name="course",
            old_name="learning_outcome",
            new_name="learning_outcome1",
        ),
        migrations.RenameField(
            model_name="course", old_name="objectives", new_name="objective1",
        ),
        migrations.RenameField(
            model_name="course", old_name="referenceb_books", new_name="objective2",
        ),
        migrations.RenameField(
            model_name="course",
            old_name="self_mearning_material",
            new_name="objective3",
        ),
        migrations.AddField(
            model_name="course",
            name="content2",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="course",
            name="content3",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="course",
            name="content4",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="course",
            name="content5",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="course",
            name="content6",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="course",
            name="content7",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="course",
            name="content8",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="course",
            name="learning_outcome2",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="course",
            name="learning_outcome3",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="course",
            name="reference_book1",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="course",
            name="reference_book2",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="course",
            name="reference_book3",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="course",
            name="reference_book4",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="course",
            name="self_mearning_material1",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="course",
            name="self_mearning_material2",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="course",
            name="self_mearning_material3",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
