# Generated by Django 4.2 on 2023-04-21 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstyear", "0008_rename_contents_course_content1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="learning_outcome1",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="course",
            name="learning_outcome2",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="course",
            name="learning_outcome3",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
