# Generated by Django 4.2 on 2023-04-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstyear", "0009_alter_course_learning_outcome1_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course", old_name="content6", new_name="activities1",
        ),
        migrations.AddField(
            model_name="course",
            name="activities2",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="course",
            name="activities3",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="course",
            name="laboratory1",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="course",
            name="laboratory10",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="course",
            name="laboratory2",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="course",
            name="laboratory3",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="course",
            name="laboratory4",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="course",
            name="laboratory5",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="course",
            name="laboratory6",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="course",
            name="laboratory7",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="course",
            name="laboratory8",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="course",
            name="laboratory9",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="course",
            name="textbook1",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="course",
            name="textbook2",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="course",
            name="textbook3",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="course",
            name="textbook4",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="course",
            name="textbook5",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="course",
            name="textbook6",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="course",
            name="content1",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="course",
            name="content2",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="course",
            name="content3",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="course",
            name="content4",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="course",
            name="content5",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="course",
            name="content7",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="course",
            name="content8",
            field=models.TextField(blank=True, default=""),
        ),
    ]
