# Generated by Django 4.2 on 2023-04-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstyear", "0010_rename_content6_course_activities1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecondSemesterCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=100)),
                (
                    "department",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("ltp", models.CharField(blank=True, default="", max_length=100)),
                (
                    "offered_for",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "course_code",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("type", models.CharField(blank=True, default="", max_length=100)),
                (
                    "prerequisite",
                    models.CharField(blank=True, default="Nil", max_length=100),
                ),
                (
                    "objective1",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "objective2",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "objective3",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "learning_outcome1",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "learning_outcome2",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "learning_outcome3",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("content1", models.TextField(blank=True, default="")),
                ("content2", models.TextField(blank=True, default="")),
                ("content3", models.TextField(blank=True, default="")),
                ("content4", models.TextField(blank=True, default="")),
                ("content5", models.TextField(blank=True, default="")),
                ("content7", models.TextField(blank=True, default="")),
                ("content8", models.TextField(blank=True, default="")),
                (
                    "laboratory1",
                    models.CharField(blank=True, default="", max_length=1000),
                ),
                (
                    "laboratory2",
                    models.CharField(blank=True, default="", max_length=1000),
                ),
                (
                    "laboratory3",
                    models.CharField(blank=True, default="", max_length=1000),
                ),
                (
                    "laboratory4",
                    models.CharField(blank=True, default="", max_length=1000),
                ),
                (
                    "laboratory5",
                    models.CharField(blank=True, default="", max_length=1000),
                ),
                (
                    "laboratory6",
                    models.CharField(blank=True, default="", max_length=1000),
                ),
                (
                    "laboratory7",
                    models.CharField(blank=True, default="", max_length=1000),
                ),
                (
                    "laboratory8",
                    models.CharField(blank=True, default="", max_length=1000),
                ),
                (
                    "laboratory9",
                    models.CharField(blank=True, default="", max_length=1000),
                ),
                (
                    "laboratory10",
                    models.CharField(blank=True, default="", max_length=1000),
                ),
                (
                    "textbook1",
                    models.CharField(blank=True, default="", max_length=1000),
                ),
                (
                    "textbook2",
                    models.CharField(blank=True, default="", max_length=1000),
                ),
                (
                    "textbook3",
                    models.CharField(blank=True, default="", max_length=1000),
                ),
                (
                    "textbook4",
                    models.CharField(blank=True, default="", max_length=1000),
                ),
                (
                    "textbook5",
                    models.CharField(blank=True, default="", max_length=1000),
                ),
                (
                    "textbook6",
                    models.CharField(blank=True, default="", max_length=1000),
                ),
                (
                    "reference_book1",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "reference_book2",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "reference_book3",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "reference_book4",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "self_mearning_material1",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "self_mearning_material2",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "self_mearning_material3",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "activities1",
                    models.CharField(blank=True, default="", max_length=1000),
                ),
                (
                    "activities2",
                    models.CharField(blank=True, default="", max_length=1000),
                ),
                (
                    "activities3",
                    models.CharField(blank=True, default="", max_length=1000),
                ),
            ],
        ),
        migrations.RenameModel(old_name="Course", new_name="FirstSemesterCourse",),
    ]
